[package]
name = "rgeometry"
version = "0.1.0"
authors = ["David Himmelstrup <lemmih@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
getrandom = { version = "^0.2.2", features = ["js"] }
num-traits = "0.1"
num-rational = "0.4"
