[package]
authors     = ["David Himmelstrup <lemmih@gmail.com>"]
categories  = ["algorithms", "data-structures", "mathematics", "graphics"]
description = "High-Level Computational Geometry"
edition     = "2018"
homepage    = "https://rgeometry.org/"
license     = "Unlicense OR BSD-2-Clause"
name        = "rgeometry"
readme      = "README.md"
repository  = "https://github.com/rgeometry/rgeometry"
version     = "0.1.0"
exclude     = [
  ".dockerignore",
  ".github",
  ".gitignore",
  "playground",
  "Dockerfile.server",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init   = "2.0"
getrandom    = { version = "^0.2.3", features = ["js"] }
num-bigint   = "0.4"
num-rational = "0.4"
num-traits   = "0.2.*"
rand         = "0.8"
