[package]
authors      = ["David Himmelstrup <lemmih@gmail.com>"]
categories   = ["algorithms", "data-structures", "mathematics", "graphics"]
description  = "High-Level Computational Geometry"
edition      = "2018"
homepage     = "https://rgeometry.org/"
license      = "Unlicense OR BSD-2-Clause"
license-file = "LICENSE"
name         = "rgeometry"
readme       = "README.md"
repository   = "https://github.com/rgeometry/rgeometry"
version      = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init   = "*"
getrandom    = { version = "^0.2.2", features = ["js"] }
num-bigint   = "*"
num-rational = "0.4"
num-traits   = "0.1"
rand         = "0.8"
