[package]
name = "rgeometry"
version = "0.1.0"
authors = ["David Himmelstrup <lemmih@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-gmp = ">=0.5.0"
rand = "0.8"
num-traits = "0.1"
